name: Deploy to EC2 (Portfolio Site)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to EC2 via SCP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "./index.html"
          target: "/home/ubuntu/"

      - name: Deploy files to Nginx folder
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mv /home/ubuntu/index.html /var/www/html/index.html
            sudo systemctl restart nginx
            echo "Deployment completed successfully ✅"
